using System.Collections.Immutable;
using ArgumentParsing.Generators.CodeGen;
using ArgumentParsing.Generators.Models;
using Microsoft.CodeAnalysis;

namespace ArgumentParsing.Generators;

public partial class ArgumentParserGenerator
{
    private const string ExcludeFromCodeCoverageAttribute = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]";

    private static void EmitArgumentParserAndHelpCommand(SourceProductionContext context, (ArgumentParserInfo ParserInfo, EnvironmentInfo EnvironmentInfo) infos)
    {
        var (parserInfo, environmentInfo) = infos;
        var (canUseOptimalSpanBasedAlgorithm, hasStringStartsWithCharOverload) = environmentInfo;

        var cancellationToken = context.CancellationToken;

        var (hierarchy, method, optionsInfo) = parserInfo;
        var (qualifiedName, hasAtLeastInternalAccessibility, optionInfos, parameterInfos, remainingParametersInfo, assemblyVersionInfo) = optionsInfo;

        var writer = new CodeWriter();

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable disable");
        writer.WriteLine("#pragma warning disable");
        writer.WriteLine();

        var generatorType = typeof(ArgumentParserGenerator);
        var generatedCodeAttribute = $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{generatorType.FullName}\", \"{generatorType.Assembly.GetName().Version}\")]";

        if (hasAtLeastInternalAccessibility)
        {
            writer.WriteLine("namespace ArgumentParsing.Generated");
            writer.OpenBlock();
            writer.WriteLine("internal static partial class ParseResultExtensions");
            writer.OpenBlock();
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Executes common default actions for the given <see cref=\"global::ArgumentParsing.Results.ParseResult{TOptions}\"/>");
            writer.WriteLine("/// <list type=\"bullet\">");
            writer.WriteLine("/// <item>If <paramref name=\"result\"/> is in <see cref=\"global::ArgumentParsing.Results.ParseResultState.ParsedOptions\"/> state invokes provided <paramref name=\"action\"/> with parsed options object</item>");
            writer.WriteLine("/// <item>If <paramref name=\"result\"/> is in <see cref=\"global::ArgumentParsing.Results.ParseResultState.ParsedWithErrors\"/> state writes help screen text with parse errors to <see cref=\"global::System.Console.Error\"/> and exits application with code 1</item>");
            writer.WriteLine("/// <item>If <paramref name=\"result\"/> is in <see cref=\"global::ArgumentParsing.Results.ParseResultState.ParsedSpecialCommand\"/> state executes parsed handler and exits application with code, returned from the handler</item>");
            writer.WriteLine("/// </list>");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"result\">Parse result</param>");
            writer.WriteLine("/// <param name=\"action\">Action, which will be invoked if options type is correctly parsed</param>");
            writer.WriteLine(generatedCodeAttribute);
            writer.WriteLine(ExcludeFromCodeCoverageAttribute);
            writer.WriteLine($"public static void ExecuteDefaults(this {method.ReturnType} result, global::System.Action<global::{optionsInfo.QualifiedTypeName}> action)");
            writer.OpenBlock();
            writer.WriteLine("switch (result.State)");
            writer.OpenBlock();
            writer.Ident++;
            writer.WriteLine("case global::ArgumentParsing.Results.ParseResultState.ParsedOptions:", identDelta: -1);
            writer.WriteLine("action(result.Options);");
            writer.WriteLine("break;");
            writer.WriteLine("case global::ArgumentParsing.Results.ParseResultState.ParsedWithErrors:", identDelta: -1);
            writer.WriteLine($"string errorScreenText = global::ArgumentParsing.Generated.HelpCommandHandler_{qualifiedName.Replace('.', '_')}.GenerateHelpText(result.Errors);");
            writer.WriteLine("global::System.Console.Error.Write(errorScreenText);");
            writer.WriteLine("global::System.Environment.Exit(1);");
            writer.WriteLine("break;");
            writer.WriteLine("case global::ArgumentParsing.Results.ParseResultState.ParsedSpecialCommand:", identDelta: -1);
            writer.WriteLine("int exitCode = result.SpecialCommandHandler.HandleCommand();");
            writer.WriteLine("global::System.Environment.Exit(exitCode);");
            writer.WriteLine("break;");
            writer.Ident--;
            writer.CloseRemainingBlocks();
            writer.WriteLine();
        }

        cancellationToken.ThrowIfCancellationRequested();

        var @namespace = hierarchy.Namespace;
        if (!string.IsNullOrEmpty(@namespace))
        {
            writer.WriteLine($"namespace {@namespace}");
            writer.OpenBlock();
        }

        foreach (var type in hierarchy.Hierarchy)
        {
            writer.WriteLine($"partial {type.GetTypeKeyword()} {type.QualifiedName}");
            writer.OpenBlock();
        }

        writer.WriteLine(generatedCodeAttribute);
        writer.WriteLine(ExcludeFromCodeCoverageAttribute);
        writer.WriteLine($"{method.Modifiers} {method.ReturnType} {method.Name}({method.ArgsParameterInfo.Type} {method.ArgsParameterInfo.Name})");
        writer.OpenBlock();

        foreach (var info in optionInfos)
        {
            writer.WriteLine(info.SequenceType switch
            {
                SequenceType.None => $"{info.Type} {info.PropertyName}_val = default({info.Type});",
                SequenceType.List => $"global::System.Collections.Generic.List<{info.Type}> {info.PropertyName}_builder = new();",
                SequenceType.ImmutableArray => $"global::System.Collections.Immutable.ImmutableArray<{info.Type}>.Builder {info.PropertyName}_builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<{info.Type}>();",
                _ => throw new InvalidOperationException("Unreachable"),
            });
        }

        foreach (var info in parameterInfos)
        {
            writer.WriteLine($"{info.Type} {info.PropertyName}_val = default({info.Type});");
        }

        if (remainingParametersInfo is not null)
        {
            writer.WriteLine(remainingParametersInfo.SequenceType switch
            {
                SequenceType.List => $"global::System.Collections.Generic.List<{remainingParametersInfo.Type}>.Builder remainingParametersBuilder = new();",
                SequenceType.ImmutableArray => $"global::System.Collections.Immutable.ImmutableArray<{remainingParametersInfo.Type}>.Builder remainingParametersBuilder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<{remainingParametersInfo.Type}>();",
                _ => throw new InvalidOperationException("Unreachable"),
            });
        }

        cancellationToken.ThrowIfCancellationRequested();

        var hasAnyOptions = optionInfos.Length > 0;
        var hasAnyParameters = parameterInfos.Length > 0;

        writer.WriteLine();
        writer.WriteLine("int state = -3;");
        if (hasAnyOptions)
        {
            writer.WriteLine("int seenOptions = 0;");
        }
        writer.WriteLine("global::System.Collections.Generic.HashSet<global::ArgumentParsing.Results.Errors.ParseError> errors = null;");
        if (canUseOptimalSpanBasedAlgorithm)
        {
            writer.WriteLine("global::System.Span<global::System.Range> longArgSplit = stackalloc global::System.Range[2];");
        }
        var spanOrString = canUseOptimalSpanBasedAlgorithm ? "global::System.ReadOnlySpan<char>" : "string";
        writer.WriteLine($"{spanOrString} latestOptionName = default({spanOrString});");
        if (hasAnyOptions)
        {
            writer.WriteLine("string previousArgument = null;");
        }
        var hasSequenceOptions = optionInfos.Any(static i => i.SequenceType != SequenceType.None);
        if (hasSequenceOptions)
        {
            writer.WriteLine("int optionSource = 0;");
        }
        if (hasAnyParameters)
        {
            writer.WriteLine("int parameterIndex = 0;");
        }
        writer.WriteLine();

        writer.WriteLine($"foreach (string arg in {method.ArgsParameterInfo.Name})");
        writer.OpenBlock();
        writer.WriteLine("if (state == -3)");
        writer.OpenBlock();
        writer.WriteLine("switch (arg)");
        writer.OpenBlock();
        writer.WriteLine("case \"--help\":");
        writer.Ident++;
        writer.WriteLine($"return new {method.ReturnType}(new global::ArgumentParsing.Generated.HelpCommandHandler_{qualifiedName.Replace('.', '_')}());");
        writer.Ident--;
        writer.WriteLine("case \"--version\":");
        writer.Ident++;
        writer.WriteLine($"return new {method.ReturnType}(new global::ArgumentParsing.Generated.VersionCommandHandler());");
        writer.Ident--;
        writer.CloseBlock();
        writer.WriteLine();
        writer.WriteLine("state = 0;");
        writer.CloseBlock();
        writer.WriteLine();
        writer.WriteLine($"{spanOrString} val;");
        writer.WriteLine();
        writer.WriteLine("bool hasLetters = global::System.Linq.Enumerable.Any(arg, char.IsLetter);");
        writer.WriteLine($"bool startsOption = hasLetters && arg.Length > 1 && {(hasStringStartsWithCharOverload ? "arg.StartsWith('-')" : "(arg[0] == '-')")};");
        writer.WriteLine();
        if (hasAnyOptions)
        {
            writer.WriteLine("if (state > 0 && startsOption)");
            writer.OpenBlock();
            writer.WriteLine("errors ??= new();");
            writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.OptionValueIsNotProvidedError(previousArgument));");
            writer.WriteLine("state = 0;");
            writer.CloseBlock();
            writer.WriteLine();
        }
        writer.WriteLine("if (state != -2)");
        writer.OpenBlock();
        writer.WriteLine("if (arg.StartsWith(\"--\") && (hasLetters || arg.Length == 2 || arg.Contains('=')))");
        writer.OpenBlock();
        writer.WriteLine($"{spanOrString} slice = {(canUseOptimalSpanBasedAlgorithm ? "global::System.MemoryExtensions.AsSpan(arg, 2)" : "arg.Substring(2)")};");
        if (canUseOptimalSpanBasedAlgorithm)
        {
            writer.WriteLine("int written = global::System.MemoryExtensions.Split(slice, longArgSplit, '=');");
        }
        else
        {
            writer.WriteLine("string[] split = slice.Split(new char[] { '=' }, count: 2);");
            writer.WriteLine("int written = split.Length;");
        }
        writer.WriteLine();
        if (hasSequenceOptions)
        {
            writer.WriteLine("optionSource = 2;");
            writer.WriteLine();
        }
        writer.WriteLine($"latestOptionName = {(canUseOptimalSpanBasedAlgorithm ? "slice[longArgSplit[0]]" : "split[0]")};");
        writer.WriteLine("switch (latestOptionName)");
        writer.OpenBlock();

        cancellationToken.ThrowIfCancellationRequested();

        writer.WriteLine("case \"\":");
        writer.Ident++;
        writer.WriteLine("if (written == 1)");
        writer.OpenBlock();
        writer.WriteLine("state = -2;");
        writer.CloseBlock();
        writer.WriteLine("else");
        writer.OpenBlock();
        writer.WriteLine("errors ??= new();");
        writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.UnrecognizedArgumentError(arg));");
        writer.CloseBlock();
        writer.WriteLine("continue;");
        writer.Ident--;

        Span<char> usageCode = stackalloc char[optionInfos.Length];

        for (var i = 0; i < optionInfos.Length; i++)
        {
            var info = optionInfos[i];

            if (info.LongName is null)
            {
                continue;
            }

            writer.WriteLine($"case \"{info.LongName}\":");
            writer.Ident++;
            usageCode.Fill('0');
            usageCode[^(i + 1)] = '1';
            writer.WriteLine($"if ((seenOptions & 0b{usageCode.ToString()}) > 0)");
            writer.OpenBlock();
            writer.WriteLine("errors ??= new();");
            writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.DuplicateOptionError(\"{info.LongName}\"));");
            writer.CloseBlock();
            if (info.ParseStrategy == ParseStrategy.Flag)
            {
                writer.WriteLine($"{info.PropertyName}_val = true;");
                writer.WriteLine($"state = {(info.NullableUnderlyingType is null ? "-10" : (int.MinValue + i))};");
            }
            else
            {
                writer.WriteLine($"state = {(info.SequenceType != SequenceType.None ? (int.MinValue + i) : i + 1)};");
            }
            writer.WriteLine($"seenOptions |= 0b{usageCode.ToString()};");
            writer.WriteLine("break;");
            writer.Ident--;
        }

        writer.WriteLine("default:");
        writer.Ident++;
        writer.WriteLine("errors ??= new();");
        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.UnknownOptionError(latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}, arg));");
        writer.WriteLine("if (written == 1)");
        writer.OpenBlock();
        writer.WriteLine("state = -1;");
        writer.CloseBlock();
        writer.WriteLine("goto continueMainLoop;");
        writer.Ident--;

        writer.CloseBlock();

        writer.WriteLine();
        writer.WriteLine("if (written == 2)");
        writer.OpenBlock();
        writer.WriteLine($"val = {(canUseOptimalSpanBasedAlgorithm ? "slice[longArgSplit[1]]" : "split[1]")};");
        writer.WriteLine("goto decodeValue;");
        writer.CloseBlock();
        writer.WriteLine();
        writer.WriteLine("goto continueMainLoop;");
        writer.CloseBlock();

        writer.WriteLine();
        writer.WriteLine("if (startsOption)");
        writer.OpenBlock();
        writer.WriteLine($"{spanOrString} slice = {(canUseOptimalSpanBasedAlgorithm ? "global::System.MemoryExtensions.AsSpan(arg, 1)" : "arg.Substring(1)")};");
        writer.WriteLine();
        if (hasSequenceOptions)
        {
            writer.WriteLine("optionSource = 1;");
            writer.WriteLine();
        }
        writer.WriteLine("for (int i = 0; i < slice.Length; i++)");
        writer.OpenBlock();
        writer.WriteLine("if (state > 0)");
        writer.OpenBlock();
        writer.WriteLine($"val = slice.{(canUseOptimalSpanBasedAlgorithm ? "Slice" : "Substring")}(i);");
        writer.WriteLine("goto decodeValue;");
        writer.CloseBlock();
        writer.WriteLine();
        writer.WriteLine("char shortOptionName = slice[i];");
        writer.WriteLine($"latestOptionName = {(canUseOptimalSpanBasedAlgorithm ? "new global::System.ReadOnlySpan<char>(in slice[i])" : "shortOptionName.ToString()")};");
        writer.WriteLine("switch (shortOptionName)");
        writer.OpenBlock();

        cancellationToken.ThrowIfCancellationRequested();

        for (var i = 0; i < optionInfos.Length; i++)
        {
            var info = optionInfos[i];

            if (!info.ShortName.HasValue)
            {
                continue;
            }

            writer.WriteLine($"case '{info.ShortName}':");
            writer.Ident++;
            usageCode.Fill('0');
            usageCode[^(i + 1)] = '1';
            writer.WriteLine($"if ((seenOptions & 0b{usageCode.ToString()}) > 0)");
            writer.OpenBlock();
            writer.WriteLine("errors ??= new();");
            writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.DuplicateOptionError(\"{info.ShortName}\"));");
            writer.CloseBlock();
            if (info.ParseStrategy == ParseStrategy.Flag)
            {
                writer.WriteLine($"{info.PropertyName}_val = true;");
                writer.WriteLine($"state = {(info.NullableUnderlyingType is null ? "-10" : (int.MinValue + i))};");
            }
            else
            {
                writer.WriteLine($"state = {(info.SequenceType != SequenceType.None ? (int.MinValue + i) : i + 1)};");
            }
            writer.WriteLine($"seenOptions |= 0b{usageCode.ToString()};");
            writer.WriteLine("break;");
            writer.Ident--;
        }

        writer.WriteLine("default:");
        writer.Ident++;
        if (optionInfos.Any(static i => i.ParseStrategy == ParseStrategy.Flag || i.SequenceType != SequenceType.None))
        {
            writer.WriteLine($"if (state <= -10)");
            writer.OpenBlock();
            if (optionInfos.Any(static i => i.NullableUnderlyingType is not null || i.SequenceType != SequenceType.None))
            {
                writer.WriteLine($"val = slice.{(canUseOptimalSpanBasedAlgorithm ? "Slice" : "Substring")}(i);");
            }
            writer.WriteLine($"latestOptionName = {(canUseOptimalSpanBasedAlgorithm ? "new global::System.ReadOnlySpan<char>(in slice[i - 1])" : "slice[i - 1].ToString()")};");
            writer.WriteLine("goto decodeValue;");
            writer.CloseBlock();
        }
        writer.WriteLine("errors ??= new();");
        writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.UnknownOptionError(shortOptionName.ToString(), arg));");
        writer.WriteLine("state = -1;");
        writer.WriteLine("goto continueMainLoop;");
        writer.Ident--;

        writer.CloseBlock();
        writer.CloseBlock();
        writer.WriteLine();
        writer.WriteLine("goto continueMainLoop;");
        writer.CloseBlock();
        writer.CloseBlock();

        writer.WriteLine();
        writer.WriteLine($"val = {(canUseOptimalSpanBasedAlgorithm ? "global::System.MemoryExtensions.AsSpan(arg)" : "arg")};");
        if (hasSequenceOptions)
        {
            writer.WriteLine("optionSource = 0;");
        }
        writer.WriteLine();

        writer.WriteLine("decodeValue:", identDelta: -1);
        writer.WriteLine("switch (state)");
        writer.OpenBlock();
        if (!hasAnyParameters && optionInfos.Any(static i => i.ParseStrategy == ParseStrategy.Flag && i.NullableUnderlyingType is null))
        {
            writer.WriteLine("case -10:");
            writer.Ident++;
            writer.WriteLine("errors ??= new();");
            writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.FlagOptionValueError(latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}));");
            writer.WriteLine("break;");
            writer.Ident--;
        }
        writer.WriteLine("case -1:");
        writer.Ident++;
        writer.WriteLine("break;");
        writer.Ident--;

        cancellationToken.ThrowIfCancellationRequested();

        for (var i = 0; i < optionInfos.Length; i++)
        {
            var info = optionInfos[i];

            var propertyName = info.PropertyName;
            var parseStrategy = info.ParseStrategy;
            var nullableUnderlyingType = info.NullableUnderlyingType;
            var sequenceType = info.SequenceType;

            if (parseStrategy == ParseStrategy.Flag && nullableUnderlyingType is null)
            {
                continue;
            }

            writer.WriteLine($"case {(parseStrategy == ParseStrategy.Flag || sequenceType != SequenceType.None ? (int.MinValue + i) : (i + 1))}:");
            writer.Ident++;
            if (sequenceType != SequenceType.None)
            {
                writer.WriteLine($"{info.Type} {propertyName}_val = default({info.Type});");
            }
            switch (parseStrategy)
            {
                case ParseStrategy.String:
                    writer.WriteLine($"{propertyName}_val = val{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)};");
                    break;
                case ParseStrategy.Integer:
                case ParseStrategy.Float:
                    if (nullableUnderlyingType is not null)
                    {
                        writer.WriteLine($"{nullableUnderlyingType} {propertyName}_underlying = default({nullableUnderlyingType});");
                    }
                    var numberStyles = parseStrategy == ParseStrategy.Integer ? "global::System.Globalization.NumberStyles.Integer" : "global::System.Globalization.NumberStyles.Float | global::System.Globalization.NumberStyles.AllowThousands";
                    writer.WriteLine($"if (!{nullableUnderlyingType ?? info.Type}.TryParse(val, {numberStyles}, global::System.Globalization.CultureInfo.InvariantCulture, out {propertyName}{(nullableUnderlyingType is not null ? "_underlying" : "_val")}))");
                    writer.OpenBlock();
                    writer.WriteLine("errors ??= new();");
                    writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadOptionValueFormatError(val{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}, latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}));");
                    writer.CloseBlock();
                    if (nullableUnderlyingType is not null)
                    {
                        writer.WriteLine($"{propertyName}_val = {propertyName}_underlying;");
                    }
                    break;
                case ParseStrategy.Flag when nullableUnderlyingType is not null:
                    writer.WriteLine($"bool {propertyName}_underlying = default({nullableUnderlyingType});");
                    writer.WriteLine($"if (!bool.TryParse(val, out {propertyName}_underlying))");
                    writer.OpenBlock();
                    writer.WriteLine("errors ??= new();");
                    writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadOptionValueFormatError(val{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}, latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}));");
                    writer.CloseBlock();
                    writer.WriteLine($"{propertyName}_val = {propertyName}_underlying;");
                    break;
                case ParseStrategy.Enum:
                    if (nullableUnderlyingType is not null)
                    {
                        writer.WriteLine($"{nullableUnderlyingType} {propertyName}_underlying = default({nullableUnderlyingType});");
                    }
                    writer.WriteLine($"if (!global::System.Enum.TryParse<{nullableUnderlyingType ?? info.Type}>(val, out {propertyName}{(nullableUnderlyingType is not null ? "_underlying" : "_val")}))");
                    writer.OpenBlock();
                    writer.WriteLine("errors ??= new();");
                    writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadOptionValueFormatError(val{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}, latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}));");
                    writer.CloseBlock();
                    if (nullableUnderlyingType is not null)
                    {
                        writer.WriteLine($"{propertyName}_val = {propertyName}_underlying;");
                    }
                    break;
                case ParseStrategy.Char:
                    writer.WriteLine($"if (val.Length == 1)");
                    writer.OpenBlock();
                    writer.WriteLine($"{propertyName}_val = val[0];");
                    writer.CloseBlock();
                    writer.WriteLine("else");
                    writer.OpenBlock();
                    writer.WriteLine("errors ??= new();");
                    writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadOptionValueFormatError(val{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}, latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}));");
                    writer.CloseBlock();
                    break;
            }
            if (sequenceType != SequenceType.None)
            {
                writer.WriteLine($"{propertyName}_builder.Add({propertyName}_val);");
                writer.WriteLine("if (optionSource > 0)");
                writer.OpenBlock();
                writer.WriteLine("state = 0;");
                writer.CloseBlock();
                writer.WriteLine("continue;");
            }
            else
            {
                writer.WriteLine("break;");
            }
            writer.Ident--;
        }

        writer.WriteLine("default:");
        writer.Ident++;
        if (hasAnyParameters)
        {
            writer.WriteLine("switch (parameterIndex++)");
            writer.OpenBlock();
            for (var i = 0; i < parameterInfos.Length; i++)
            {
                var info = parameterInfos[i];
                var propertyName = info.PropertyName;
                var parseStrategy = info.ParseStrategy;
                var nullableUnderlyingType = info.NullableUnderlyingType;

                writer.WriteLine($"case {i}:");
                writer.Ident++;
                switch (parseStrategy)
                {
                    case ParseStrategy.String:
                        writer.WriteLine($"{propertyName}_val = arg;");
                        break;
                    case ParseStrategy.Integer:
                    case ParseStrategy.Float:
                        if (nullableUnderlyingType is not null)
                        {
                            writer.WriteLine($"{nullableUnderlyingType} {propertyName}_underlying = default({nullableUnderlyingType});");
                        }
                        var numberStyles = parseStrategy == ParseStrategy.Integer ? "global::System.Globalization.NumberStyles.Integer" : "global::System.Globalization.NumberStyles.Float | global::System.Globalization.NumberStyles.AllowThousands";
                        writer.WriteLine($"if (!{nullableUnderlyingType ?? info.Type}.TryParse(val, {numberStyles}, global::System.Globalization.CultureInfo.InvariantCulture, out {propertyName}{(nullableUnderlyingType is not null ? "_underlying" : "_val")}))");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadParameterValueFormatError(arg, \"{info.Name}\", parameterIndex - 1));");
                        writer.CloseBlock();
                        if (nullableUnderlyingType is not null)
                        {
                            writer.WriteLine($"{propertyName}_val = {propertyName}_underlying;");
                        }
                        break;
                    case ParseStrategy.Flag:
                        if (nullableUnderlyingType is not null)
                        {
                            writer.WriteLine($"{nullableUnderlyingType} {propertyName}_underlying = default({nullableUnderlyingType});");
                        }
                        writer.WriteLine($"if (!bool.TryParse(arg, out {propertyName}{(nullableUnderlyingType is not null ? "_underlying" : "_val")}))");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadParameterValueFormatError(arg, \"{info.Name}\", parameterIndex - 1));");
                        writer.CloseBlock();
                        if (nullableUnderlyingType is not null)
                        {
                            writer.WriteLine($"{propertyName}_val = {propertyName}_underlying;");
                        }
                        break;
                    case ParseStrategy.Enum:
                        if (nullableUnderlyingType is not null)
                        {
                            writer.WriteLine($"{nullableUnderlyingType} {propertyName}_underlying = default({nullableUnderlyingType});");
                        }
                        writer.WriteLine($"if (!global::System.Enum.TryParse<{nullableUnderlyingType ?? info.Type}>(arg, out {propertyName}{(nullableUnderlyingType is not null ? "_underlying" : "_val")}))");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadParameterValueFormatError(arg, \"{info.Name}\", parameterIndex - 1));");
                        writer.CloseBlock();
                        if (nullableUnderlyingType is not null)
                        {
                            writer.WriteLine($"{propertyName}_val = {propertyName}_underlying;");
                        }
                        break;
                    case ParseStrategy.Char:
                        writer.WriteLine($"if (arg.Length == 1)");
                        writer.OpenBlock();
                        writer.WriteLine($"{propertyName}_val = arg[0];");
                        writer.CloseBlock();
                        writer.WriteLine("else");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadParameterValueFormatError(arg, \"{info.Name}\", parameterIndex - 1));");
                        writer.CloseBlock();
                        break;
                }
                writer.WriteLine("break;");
                writer.Ident--;
            }
            writer.WriteLine("default:");
            writer.Ident++;
            if (remainingParametersInfo is null)
            {
                if (optionInfos.Any(static i => i.ParseStrategy == ParseStrategy.Flag && i.NullableUnderlyingType is null))
                {
                    writer.WriteLine("errors ??= new();");
                    writer.WriteLine("if (state == -10)");
                    writer.OpenBlock();
                    writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.FlagOptionValueError(latestOptionName{(canUseOptimalSpanBasedAlgorithm ? ".ToString()" : string.Empty)}));");
                    writer.CloseBlock();
                    writer.WriteLine("else");
                    writer.OpenBlock();
                    writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.UnrecognizedArgumentError(arg));");
                    writer.CloseBlock();
                }
                else
                {
                    writer.WriteLine("errors ??= new();");
                    writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.UnrecognizedArgumentError(arg));");
                }
            }
            else
            {
                var propertyName = remainingParametersInfo.PropertyName;
                var type = remainingParametersInfo.Type;
                var parseStrategy = remainingParametersInfo.ParseStrategy;
                switch (parseStrategy)
                {
                    case ParseStrategy.String:
                        writer.WriteLine("remainingParametersBuilder.Add(arg);");
                        break;
                    case ParseStrategy.Integer:
                    case ParseStrategy.Float:
                        writer.WriteLine($"{type} {propertyName}_val = default({type});");
                        var numberStyles = parseStrategy == ParseStrategy.Integer ? "global::System.Globalization.NumberStyles.Integer" : "global::System.Globalization.NumberStyles.Float | global::System.Globalization.NumberStyles.AllowThousands";
                        writer.WriteLine($"if (!{type}.TryParse(val, {numberStyles}, global::System.Globalization.CultureInfo.InvariantCulture, out {propertyName}_val))");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadRemainingParameterValueFormatError(arg, parameterIndex - 1));");
                        writer.CloseBlock();
                        writer.WriteLine($"remainingParametersBuilder.Add({propertyName}_val);");
                        break;
                    case ParseStrategy.Flag:
                        writer.WriteLine($"bool {propertyName}_val = default(bool);");
                        writer.WriteLine($"if (!bool.TryParse(arg, out {propertyName}_val))");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadRemainingParameterValueFormatError(arg, parameterIndex - 1));");
                        writer.CloseBlock();
                        writer.WriteLine($"remainingParametersBuilder.Add({propertyName}_val);");
                        break;
                    case ParseStrategy.Enum:
                        writer.WriteLine($"{type} {propertyName}_val = default({type});");
                        writer.WriteLine($"if (!global::System.Enum.TryParse<{type}>(arg, out {propertyName}_val))");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadRemainingParameterValueFormatError(arg, parameterIndex - 1));");
                        writer.CloseBlock();
                        writer.WriteLine($"remainingParametersBuilder.Add({propertyName}_val);");
                        break;
                    case ParseStrategy.Char:
                        writer.WriteLine($"if (arg.Length == 1)");
                        writer.OpenBlock();
                        writer.WriteLine($"remainingParametersBuilder.Add(arg[0]);");
                        writer.CloseBlock();
                        writer.WriteLine("else");
                        writer.OpenBlock();
                        writer.WriteLine("errors ??= new();");
                        writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.BadRemainingParameterValueFormatError(arg, parameterIndex - 1));");
                        writer.CloseBlock();
                        break;
                }
            }
            writer.WriteLine("break;");
            writer.Ident--;
            writer.CloseBlock();
        }
        else
        {
            writer.WriteLine("errors ??= new();");
            writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.UnrecognizedArgumentError(arg));");
        }
        writer.WriteLine("break;");
        writer.Ident--;

        writer.CloseBlock();

        writer.WriteLine();
        writer.WriteLine("state = 0;");

        writer.WriteLine();
        writer.WriteLine("continueMainLoop:", identDelta: -1);
        if (hasAnyOptions)
        {
            writer.WriteLine("previousArgument = arg;");
        }
        else
        {
            writer.WriteLine(";");
        }
        writer.CloseBlock();

        if (hasAnyOptions)
        {
            writer.WriteLine();
            writer.WriteLine("if (state > 0)");
            writer.OpenBlock();
            writer.WriteLine("errors ??= new();");
            writer.WriteLine("errors.Add(new global::ArgumentParsing.Results.Errors.OptionValueIsNotProvidedError(previousArgument));");
            writer.CloseBlock();
        }

        for (var i = 0; i < optionInfos.Length; i++)
        {
            var info = optionInfos[i];

            if (info.IsRequired)
            {
                writer.WriteLine();
                usageCode.Fill('0');
                usageCode[^(i + 1)] = '1';
                writer.WriteLine($"if ((seenOptions & 0b{usageCode.ToString()}) == 0)");
                writer.OpenBlock();
                writer.WriteLine("errors ??= new();");
                writer.WriteLine((info.ShortName, info.LongName) switch
                {
                    (not null, null) => $"errors.Add(new global::ArgumentParsing.Results.Errors.MissingRequiredOptionError('{info.ShortName.Value}'));",
                    (null, not null) => $"errors.Add(new global::ArgumentParsing.Results.Errors.MissingRequiredOptionError(\"{info.LongName}\"));",
                    (not null, not null) => $"errors.Add(new global::ArgumentParsing.Results.Errors.MissingRequiredOptionError('{info.ShortName.Value}', \"{info.LongName}\"));",
                    _ => throw new InvalidOperationException("Unreachable"),
                });
                writer.CloseBlock();
            }
        }

        for (var i = 0; i < parameterInfos.Length; i++)
        {
            var info = parameterInfos[i];

            if (info.IsRequired)
            {
                writer.WriteLine();
                writer.WriteLine($"if (parameterIndex <= {i})");
                writer.OpenBlock();
                writer.WriteLine("errors ??= new();");
                writer.WriteLine($"errors.Add(new global::ArgumentParsing.Results.Errors.MissingRequiredParameterError(\"{info.Name}\", {i}));");
                writer.CloseBlock();
            }
        }

        writer.WriteLine();
        writer.WriteLine("if (errors != null)");
        writer.OpenBlock();
        writer.WriteLine($"return new {method.ReturnType}(global::ArgumentParsing.Results.Errors.ParseErrorCollection.AsErrorCollection(errors));");
        writer.CloseBlock();

        var optionsType = $"global::{qualifiedName}";
        writer.WriteLine();
        writer.WriteLine($"{optionsType} options = new {optionsType}");
        writer.OpenBlock();

        foreach (var info in optionInfos)
        {
            writer.WriteLine($"{info.PropertyName} = {info.PropertyName}{(info.SequenceType != SequenceType.None ? "_builder" : "_val")}{(info.SequenceType == SequenceType.ImmutableArray ? ".ToImmutable()" : string.Empty)},");
        }

        foreach (var info in parameterInfos)
        {
            writer.WriteLine($"{info.PropertyName} = {info.PropertyName}_val,");
        }

        if (remainingParametersInfo is not null)
        {
            writer.WriteLine($"{remainingParametersInfo.PropertyName} = {remainingParametersInfo.SequenceType switch
            {
                SequenceType.List => "remainingParametersBuilder",
                SequenceType.ImmutableArray => "remainingParametersBuilder.ToImmutable()",
                _ => throw new InvalidOperationException("Unreachable"),
            }},");
        }

        writer.Ident--;
        writer.WriteLine("};");
        writer.WriteLine();

        writer.WriteLine($"return new {method.ReturnType}(options);");
        writer.CloseBlock();

        writer.CloseRemainingBlocks();

        context.AddSource($"{qualifiedName}.g.cs", writer.ToString().Trim());

        cancellationToken.ThrowIfCancellationRequested();

        var helpWriter = new CodeWriter();

        helpWriter.WriteLine("// <auto-generated/>");
        helpWriter.WriteLine("#nullable disable");
        helpWriter.WriteLine("#pragma warning disable");
        helpWriter.WriteLine();
        helpWriter.WriteLine("namespace ArgumentParsing.Generated");
        helpWriter.OpenBlock();
        helpWriter.WriteLine("/// <summary>");
        helpWriter.WriteLine($"/// Default implementation of <c>--help</c> command for <see cref=\"global::{qualifiedName}\"/> type");
        helpWriter.WriteLine("/// </summary>");
        helpWriter.WriteLine("[global::ArgumentParsing.SpecialCommands.SpecialCommandAliasesAttribute(\"--help\")]");
        helpWriter.WriteLine(generatedCodeAttribute);
        helpWriter.WriteLine(ExcludeFromCodeCoverageAttribute);
        helpWriter.WriteLine($"internal sealed class HelpCommandHandler_{qualifiedName.Replace('.', '_')} : global::ArgumentParsing.SpecialCommands.ISpecialCommandHandler");
        helpWriter.OpenBlock();
        helpWriter.WriteLine("/// <summary>");
        helpWriter.WriteLine($"/// Generates help text for <see cref=\"global::{qualifiedName}\"/> type.");
        helpWriter.WriteLine("/// If <paramref name=\"errors\"/> parameter is supplied, generated text will contain an error section");
        helpWriter.WriteLine("/// </summary>");
        helpWriter.WriteLine("/// <remarks>");
        helpWriter.WriteLine("/// Help text, produced by this method, already contains a trailing new line.");
        helpWriter.WriteLine("/// In order to avoid double trailing new line problem, use <c>Write</c> method instead of <c>WriteLine</c> when writing this text to console or other text writers");
        helpWriter.WriteLine("/// </remarks>");
        helpWriter.WriteLine("/// <param name=\"errors\">Parse errors to include into help text</param>");
        helpWriter.WriteLine("/// <returns>Generated help text with included trailing new line</returns>");
        helpWriter.WriteLine("public static string GenerateHelpText(global::ArgumentParsing.Results.Errors.ParseErrorCollection? errors = null)");
        helpWriter.OpenBlock();
        helpWriter.WriteLine("global::System.Text.StringBuilder helpBuilder = new();");
        helpWriter.WriteLine($"helpBuilder.AppendLine(\"{assemblyVersionInfo.Name} {assemblyVersionInfo.Version.ToString(3)}\");");
        helpWriter.WriteLine("helpBuilder.AppendLine(\"Copyright (C) \" + global::System.DateTime.UtcNow.Year.ToString());");
        helpWriter.WriteLine("helpBuilder.AppendLine();");
        helpWriter.WriteLine("if ((object)errors != null)");
        helpWriter.OpenBlock();
        helpWriter.WriteLine("helpBuilder.AppendLine(\"ERROR(S):\");");
        helpWriter.WriteLine("foreach (global::ArgumentParsing.Results.Errors.ParseError error in errors)");
        helpWriter.OpenBlock();
        helpWriter.WriteLine("helpBuilder.AppendLine(\"  \" + error.GetMessage());");
        helpWriter.CloseBlock();
        helpWriter.WriteLine("helpBuilder.AppendLine();");
        helpWriter.CloseBlock();
        if (hasAnyOptions)
        {
            helpWriter.WriteLine("helpBuilder.AppendLine(\"OPTIONS:\");");
            foreach (var info in optionInfos)
            {
                helpWriter.WriteLine("helpBuilder.AppendLine();");
                helpWriter.Write("helpBuilder.AppendLine(\"  ");
                if (info.ShortName.HasValue)
                {
                    helpWriter.Write($"-{info.ShortName.Value}");
                }
                if (info.ShortName.HasValue && info.LongName is not null)
                {
                    helpWriter.Write(", ");
                }
                if (info.LongName is not null)
                {
                    helpWriter.Write($"--{info.LongName}");
                }
                if (info.HelpDescription is not null)
                {
                    helpWriter.Write("\\t" + info.HelpDescription);
                }
                helpWriter.WriteLine("\");");
            }
        }
        if (hasAnyParameters)
        {
            helpWriter.WriteLine("helpBuilder.AppendLine();");
            helpWriter.WriteLine("helpBuilder.AppendLine(\"PARAMETERS:\");");
            for (var i = 0; i < parameterInfos.Length; i++)
            {
                var info = parameterInfos[i];

                helpWriter.WriteLine("helpBuilder.AppendLine();");
                helpWriter.Write($"helpBuilder.AppendLine(\"  {info.Name} (at index {i})");
                if (info.HelpDescription is not null)
                {
                    helpWriter.Write($"\\t{info.HelpDescription}");
                }
                helpWriter.WriteLine("\");");
            }
        }
        if (remainingParametersInfo is not null)
        {
            helpWriter.WriteLine("helpBuilder.AppendLine();");
            helpWriter.Write("helpBuilder.AppendLine(\"  Remaining parameters");
            if (remainingParametersInfo.HelpDescription is not null)
            {
                helpWriter.Write($"\\t{remainingParametersInfo.HelpDescription}");
            }
            helpWriter.WriteLine("\");");
        }
        helpWriter.WriteLine("helpBuilder.AppendLine();");
        helpWriter.WriteLine("helpBuilder.AppendLine(\"COMMANDS:\");");
        helpWriter.WriteLine("helpBuilder.AppendLine();");
        helpWriter.WriteLine("helpBuilder.AppendLine(\"  --help\\tShow help screen\");");
        helpWriter.WriteLine("helpBuilder.AppendLine();");
        helpWriter.WriteLine("helpBuilder.AppendLine(\"  --version\\tShow version information\");");
        helpWriter.WriteLine("return helpBuilder.ToString();");
        helpWriter.CloseBlock();
        helpWriter.WriteLine();
        helpWriter.WriteLine("/// <inheritdoc/>");
        helpWriter.WriteLine("public int HandleCommand()");
        helpWriter.OpenBlock();
        helpWriter.WriteLine("global::System.Console.Out.Write(GenerateHelpText());");
        helpWriter.WriteLine("return 0;");
        helpWriter.CloseRemainingBlocks();

        context.AddSource($"HelpCommandHandler.{qualifiedName}.g.cs", helpWriter.ToString().Trim());
    }

    private static void EmitVersionCommandHandlers(SourceProductionContext context, ImmutableArray<AssemblyVersionInfo> assemblyVersionInfos)
    {
        var generatorType = typeof(ArgumentParserGenerator);
        var generatedCodeAttribute = $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{generatorType.FullName}\", \"{generatorType.Assembly.GetName().Version}\")]";

        foreach (var versionInfo in assemblyVersionInfos.Distinct())
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var command = $$"""
                // <auto-generated/>
                #nullable disable
                #pragma warning disable

                namespace ArgumentParsing.Generated
                {
                    /// <summary>
                    /// Default implementation of <c>--version</c> command for <c>{{versionInfo.Name}}</c> assembly
                    /// </summary>
                    [global::ArgumentParsing.SpecialCommands.SpecialCommandAliasesAttribute("--version")]
                    {{generatedCodeAttribute}}
                    {{ExcludeFromCodeCoverageAttribute}}
                    internal sealed class VersionCommandHandler : global::ArgumentParsing.SpecialCommands.ISpecialCommandHandler
                    {
                        /// <inheritdoc/>
                        public int HandleCommand()
                        {
                            global::System.Console.WriteLine("{{versionInfo.Name}} {{versionInfo.Version.ToString(3)}}");
                            return 0;
                        }
                    }
                }
                """;

            context.AddSource($"VersionCommandHandler.{versionInfo.Name}.g.cs", command);
        }
    }
}
